namespace GlitchInTheSystem.GameData
{
    /// <summary>
    /// Additional hand-authored queue captions (Step 3). Merged into <see cref="ModerationContentPools.AllQueueEntries"/>.
    /// No runtime text generation — each line is written in a distinct voice.
    /// </summary>
    public static class ModerationContentPoolsExtended
    {
        public static readonly ModerationContentPools.ModerationEntry[] AdditionalQueueEntries =
        {
            new(
                "ok so my manager scheduled a 7am 'optional' meeting… again. love that for me",
                "i just think this is mean / workplace stuff??",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.GrayArea,
                1,
                reporterTone: ReporterTone.OpinionBased,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "PSA: the northside clinic still has walk-in flu shots til 6. bring ID.",
                "helpful local info — flagged by mistake?",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Harmless,
                0,
                reporterTone: ReporterTone.FalseReport,
                reportCredibility: ReportCredibility.LikelyFalseReport),
            new(
                "BREAKING!!! water department switching additives AGAIN read before they delete",
                "This post is spreading false medical information about municipal water.",
                "Screenshot of blurry PDF header, no agency seal.",
                PostPresentationFormat.TextWithImageDescription,
                PostCategory.Misinformation,
                3,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "literally crying in the break room rn. if you know you know.",
                "Concerned about self-harm tone — unclear if real.",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.GrayArea,
                2,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "Dear Platform Team: I am writing to formally dispute the removal of my gardening thread.",
                "Appeal — user cites community guidelines section 4.2",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Harmless,
                0,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "nah the election megathread is wild today… ppl fighting in quotes for sport",
                "Brigading in replies",
                null,
                PostPresentationFormat.TextWithAttachedComments,
                PostCategory.GrayArea,
                1,
                reporterTone: ReporterTone.Vague,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "they dont want u to know abt the bus route changes… spread b4 monday",
                "Unverified transit rumor — may cause panic commuting",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Misinformation,
                2,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "✨✨ BEST DAY EVER ✨✨ got free pastries bc i smiled at the barista lol #blessed",
                "spam",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Harmless,
                0,
                reporterTone: ReporterTone.FalseReport,
                reportCredibility: ReportCredibility.LikelyFalseReport),
            new(
                "Congrats!! u won $500 gift card click link in bio (totally legit)",
                "Obvious phishing — gift card scam pattern",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Violation,
                3,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "If the county really cared about safety they wouldn't hide the inspection scores… just saying.",
                "User reports 'panic inducing' — no specific rule cited",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Narrative,
                2,
                reporterTone: ReporterTone.OpinionBased,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "photo dump from the protest — blurry but you can see the badge numbers",
                "Doxxing risk in images",
                "Three shaky photos, faces partially visible.",
                PostPresentationFormat.TextWithImageDescription,
                PostCategory.GrayArea,
                2,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "my neighbor's smoke alarm went off at 3am and now i'm awake AND mad",
                "idk",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Harmless,
                0,
                reporterTone: ReporterTone.Vague,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "Algorithm boosted my joke meme to 90k views but buried the charity drive. cool cool cool.",
                "Author documents suspicious engagement spikes",
                "Line chart screenshot, axes unlabeled.",
                PostPresentationFormat.TextWithImageDescription,
                PostCategory.AlgorithmManipulation,
                1,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "thread: why the 'harmless' policy update is NOT harmless (long read)",
                "political opinion disguised as policy analysis?",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.GrayArea,
                1,
                reporterTone: ReporterTone.OpinionBased,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "stop sharing that celebrity death hoax omg they posted 20 minutes ago",
                "Rumor control — possible harassment of public figure",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Harmless,
                0,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "I am NOT saying it's aliens… but the timeline doesn't line up…",
                "idk feels like propaganda",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Narrative,
                1,
                reporterTone: ReporterTone.Vague,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "DM me for exclusive investment tips 📈📈 100% returns (not financial advice lol)",
                "Scam / prohibited goods",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.Violation,
                3,
                reporterTone: ReporterTone.Genuine,
                reportCredibility: ReportCredibility.Credible),
            new(
                "Anyone else's feed nothing but rage bait since the update or is it just me",
                "Complaint about product — not a policy violation?",
                null,
                PostPresentationFormat.TextOnly,
                PostCategory.AlgorithmManipulation,
                0,
                reporterTone: ReporterTone.OpinionBased,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "lost cat: orange tabby answers to 'Cheeto' — reward if found please share",
                "none",
                "Photo: cat on porch, slightly blurry.",
                PostPresentationFormat.TextWithImageDescription,
                PostCategory.Harmless,
                0,
                reporterTone: ReporterTone.Vague,
                reportCredibility: ReportCredibility.Unclear),
            new(
                "they're laughing at us in the comments. wake up.",
                "Hate speech in replies (caption vague)",
                null,
                PostPresentationFormat.TextWithAttachedComments,
                PostCategory.Misinformation,
                2,
                reporterTone: ReporterTone.Vague,
                reportCredibility: ReportCredibility.Unclear)
        };
    }
}
